//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4200
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insta.Project.CI.UnitTests.LecteurRSS.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insta.Project.CI.UnitTests.LecteurRSS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///	&lt;title&gt;Example Feed&lt;/title&gt;
        ///	&lt;link href=&quot;http://example.org/&quot;/&gt;
        ///	&lt;updated&gt;2003-12-13T18:30:02Z&lt;/updated&gt;
        ///	&lt;author&gt;
        ///		&lt;name&gt;John Doe&lt;/name&gt;
        ///	&lt;/author&gt;
        ///	&lt;id&gt;urn:uuid:60a76c80-d399-11d9-b93C-0003939e0af6&lt;/id&gt;
        ///	&lt;entry&gt;
        ///		&lt;title&gt;Atom-Powered Robots Run Amok&lt;/title&gt;
        ///		&lt;link href=&quot;http://example.org/2003/12/13/atom03&quot;/&gt;
        ///		&lt;id&gt;urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a&lt;/id&gt;
        ///		&lt;updated&gt;2003-12-13T18:30:02Z&lt;/updated&gt;
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string sampleAtom1 {
            get {
                return ResourceManager.GetString("sampleAtom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///&lt;rss version=&quot;0.91&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;title&gt;WriteTheWeb&lt;/title&gt; 
        ///		&lt;link&gt;http://writetheweb.com&lt;/link&gt; 
        ///		&lt;description&gt;News for web users that write back&lt;/description&gt; 
        ///		&lt;language&gt;en-us&lt;/language&gt; 
        ///		&lt;copyright&gt;Copyright 2000, WriteTheWeb team.&lt;/copyright&gt; 
        ///		&lt;managingEditor&gt;editor@writetheweb.com&lt;/managingEditor&gt; 
        ///		&lt;webMaster&gt;webmaster@writetheweb.com&lt;/webMaster&gt; 
        ///		&lt;image&gt;
        ///			&lt;title&gt;WriteTheWeb&lt;/title&gt; 
        ///			&lt;url&gt;http://writetheweb.com/images/mynetscap [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string sampleRss091 {
            get {
                return ResourceManager.GetString("sampleRss091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- RSS generation done by &apos;Radio UserLand&apos; on Fri, 13 Apr 2001 19:23:02 GMT --&gt;
        ///&lt;rss version=&quot;0.92&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;title&gt;Dave Winer: Grateful Dead&lt;/title&gt;
        ///		&lt;link&gt;http://www.scripting.com/blog/categories/gratefulDead.html&lt;/link&gt;
        ///		&lt;description&gt;A high-fidelity Grateful Dead song every day. This is where we&amp;apos;re experimenting with enclosures on RSS news items that download when you&amp;apos;re not using your computer. If it works (it will) it will be the end of the Click-And-Wait  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string sampleRss092 {
            get {
                return ResourceManager.GetString("sampleRss092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///   &lt;channel&gt;
        ///      &lt;title&gt;Liftoff News&lt;/title&gt;
        ///      &lt;link&gt;http://liftoff.msfc.nasa.gov/&lt;/link&gt;
        ///      &lt;description&gt;Liftoff to Space Exploration.&lt;/description&gt;
        ///      &lt;language&gt;en-us&lt;/language&gt;
        ///      &lt;pubDate&gt;Tue, 10 Jun 2003 04:00:00 GMT&lt;/pubDate&gt;
        ///      &lt;lastBuildDate&gt;Tue, 10 Jun 2003 09:41:01 GMT&lt;/lastBuildDate&gt;
        ///      &lt;docs&gt;http://blogs.law.harvard.edu/tech/rss&lt;/docs&gt;
        ///      &lt;generator&gt;Weblog Editor 2.0&lt;/generator&gt;
        ///      &lt;managingEditor&gt;editor@example.com&lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string sampleRss2 {
            get {
                return ResourceManager.GetString("sampleRss2", resourceCulture);
            }
        }
    }
}
